#############################################################################
# Makefile for building multiboost
# Generated by tmake at 14:23, 2007/02/16
#     Project: multiboost
#    Template: app
#############################################################################

####### Compiler, tools and options

QTDIR	=	/usr
CC	=	gcc
CXX	=	g++
CFLAGS	=	-pipe -O2 -DNDEBUG
CXXFLAGS=	-pipe -O2 -DNDEBUG
INCPATH	=	-Isrc
LINK	=	g++
LFLAGS	=	
LIBS	=	$(SUBLIBS) 
MOC	=	$(QTDIR)/bin/moc
UIC	=	$(QTDIR)/bin/uic

TAR	=	tar -cf
GZIP	=	gzip -9f

####### Files

HEADERS =	src/Defaults.h \
		src/StrongLearners/GenericStrongLearner.h \
		src/StrongLearners/AdaBoostMHLearner.h \
		src/Classifiers/AdaBoostMHClassifier.h \
		src/Classifiers/ExampleResults.h \
		src/Algorithms/ConstantAlgorithm.h \
		src/Algorithms/ConstantAlgorithmLSHTC.h \
		src/Algorithms/StumpAlgorithm.h \
		src/Algorithms/StumpAlgorithmLSHTC.h \
		src/Algorithms/SparseStumpAlgorithm.h \
		src/IO/NameMap.h \
		src/IO/InputData.h \
		src/IO/RawData.h \
		src/IO/EncodeData.h \
		src/IO/OutputInfo.h \
		src/IO/Serialization.h \
		src/IO/SortedData.h \
		src/IO/HaarData.h \
		src/IO/GenericParser.h \
		src/IO/TxtParser.h \
		src/IO/ArffParser.h \
		src/IO/LSHTCParser.h \
		src/IO/ArffParserBzip2.h \
		src/Bzip2/Bzip2Wrapper.h \
		src/Bzip2/bzlib.h \
		src/Bzip2/bzlib_private.h \
		src/Utils/Args.h \
		src/Utils/StreamTokenizer.h \
		src/Utils/ClassHierarchy.h \
		src/Utils/Utils.h \
		src/Utils/UCTutils.h \
		src/Bandits/GenericBanditAlgorithm.h \
		src/Bandits/UCBK.h \
		src/Bandits/UCBKV.h \
		src/Bandits/UCBKRandomized.h \
		src/Bandits/Random.h \
		src/Bandits/Exp3.h \
		src/Bandits/Exp3G.h \
		src/Others/Rates.h \
		src/Others/Example.h \
		src/WeakLearners/BaseLearner.h \
		src/WeakLearners/AbstainableLearner.h \
		src/WeakLearners/FeaturewisLearner.h \
		src/WeakLearners/ConstantLearner.h \
		src/WeakLearners/SingleStumpLearner.h \
		src/WeakLearners/SingleStumpLearnerLSHTC.h \
		src/WeakLearners/RandomSingleStumpLearner.h \
		src/WeakLearners/UCB1SingleStumpLearner.h \
		src/WeakLearners/UCBKSingleStumpLearner.h \
		src/WeakLearners/BanditSingleStumpLearner.h \
		src/WeakLearners/UCBKSingleStumpLearnerLSHTC.h \
		src/WeakLearners/UCBVHaarSingleStumpLearner.h \
		src/WeakLearners/DirichletSingleStumpLearner.h \
		src/WeakLearners/MultiStumpLearner.h \
		src/WeakLearners/ParasiteLearner.h \
		src/WeakLearners/ProductLearner.h \
		src/WeakLearners/ProductLearnerLSHTC.h \
		src/WeakLearners/ProductLearnerUCT.h \
		src/WeakLearners/TreeLearner.h \
		src/WeakLearners/TreeLearnerUCT.h \
		src/WeakLearners/EnumLearner.h \
		src/WeakLearners/Selector.h \
		src/WeakLearners/Haar/HaarLearner.h \
		src/WeakLearners/Haar/HaarFeatures.h \
		src/WeakLearners/HaarSingleStumpLearner.h \
		src/WeakLearners/HaarMultiStumpLearner.h \
SOURCES =	src/StrongLearners/AdaBoostMHLearner.cpp \
		src/Classifiers/AdaBoostMHClassifier.cpp \
		src/Classifiers/ExampleResults.cpp \
		src/Algorithms/ConstantAlgorithm.cpp \
		src/Algorithms/ConstantAlgorithmLSHTC.cpp \
		src/IO/NameMap.cpp \
		src/IO/InputData.cpp \
		src/IO/RawData.cpp \
		src/IO/EncodeData.cpp \
		src/IO/OutputInfo.cpp \
		src/IO/Serialization.cpp \
		src/IO/SortedData.cpp \
		src/IO/HaarData.cpp \
		src/IO/TxtParser.cpp \
		src/IO/ArffParser.cpp \
		src/IO/LSHTCParser.cpp \
		src/IO/ArffParserBzip2.cpp \
		src/Bzip2/Bzip2Wrapper.cpp \
		src/Bzip2/blocksort.c \
		src/Bzip2/bzip2.c \
		src/Bzip2/bzip2recover.c \
		src/Bzip2/bzlib.c \
		src/Bzip2/compress.c \
		src/Bzip2/crctable.c \
		src/Bzip2/decompress.c \
		src/Bzip2/dlltest.c \
		src/Bzip2/huffman.c \
		src/Bzip2/mk251.c \
		src/Bzip2/randtable.c \
		src/Bzip2/spewG.c \
		src/Bzip2/unzcrash.c \
		src/Utils/Args.cpp \
		src/Utils/ClassHierarchy.cpp \
		src/Utils/Utils.cpp \
		src/Utils/UCTutils.cpp \
		src/Bandits/GenericBanditAlgorithm.cpp \
		src/Bandits/UCBK.cpp \
		src/Bandits/UCBKV.cpp \
		src/Bandits/UCBKRandomized.cpp \
		src/Bandits/Random.cpp \
		src/Bandits/Exp3.cpp \
		src/Bandits/Exp3G.cpp \
		src/WeakLearners/BaseLearner.cpp \
		src/WeakLearners/ConstantLearner.cpp \
		src/WeakLearners/FeaturewiseLearner.cpp \
		src/WeakLearners/AbstainableLearner.cpp \
		src/WeakLearners/SingleStumpLearner.cpp \
		src/WeakLearners/SingleStumpLearnerLSHTC.cpp \
		src/WeakLearners/RandomSingleStumpLearner.cpp \
		src/WeakLearners/UCB1SingleStumpLearner.cpp \
		src/WeakLearners/UCBKSingleStumpLearner.cpp \
		src/WeakLearners/BanditSingleStumpLearner.cpp \
		src/WeakLearners/UCBKSingleStumpLearnerLSHTC.cpp \
		src/WeakLearners/UCBVHaarSingleStumpLearner.cpp \
		src/WeakLearners/DirichletSingleStumpLearner.cpp \
		src/WeakLearners/MultiStumpLearner.cpp \
		src/WeakLearners/ParasiteLearner.cpp \
		src/WeakLearners/ProductLearner.cpp \
		src/WeakLearners/ProductLearnerLSHTC.cpp \
		src/WeakLearners/ProductLearnerUCT.cpp \
		src/WeakLearners/TreeLearner.cpp \
		src/WeakLearners/TreeLearnerUCT.cpp \
		src/WeakLearners/EnumLearner.cpp \
		src/WeakLearners/Selector.cpp \
		src/WeakLearners/Haar/HaarLearner.cpp \
		src/WeakLearners/Haar/HaarFeatures.cpp \
		src/WeakLearners/HaarSingleStumpLearner.cpp \
		src/WeakLearners/HaarMultiStumpLearner.cpp \
		src/main.cpp
OBJECTS =	src/StrongLearners/AdaBoostMHLearner.o \
		src/Classifiers/AdaBoostMHClassifier.o \
		src/Classifiers/ExampleResults.o \
		src/Algorithms/ConstantAlgorithm.o \
		src/Algorithms/ConstantAlgorithmLSHTC.o \
		src/IO/NameMap.o \
		src/IO/InputData.o \
		src/IO/RawData.o \
		src/IO/EncodeData.o \
		src/IO/OutputInfo.o \
		src/IO/Serialization.o \
		src/IO/SortedData.o \
		src/IO/HaarData.o \
		src/IO/TxtParser.o \
		src/IO/ArffParser.o \
		src/IO/LSHTCParser.o \
		src/IO/ArffParserBzip2.o \
		src/Bzip2/Bzip2Wrapper.o \
		src/Bzip2/blocksort.o \
		src/Bzip2/bzip2.o \
		src/Bzip2/bzip2recover.o \
		src/Bzip2/bzlib.o \
		src/Bzip2/compress.o \
		src/Bzip2/crctable.o \
		src/Bzip2/decompress.o \
		src/Bzip2/dlltest.o \
		src/Bzip2/huffman.o \
		src/Bzip2/mk251.o \
		src/Bzip2/randtable.o \
		src/Bzip2/spewG.o \
		src/Bzip2/unzcrash.o \
		src/Utils/Args.o \
		src/Utils/ClassHierarchy.o \
		src/Utils/Utils.o \
		src/Utils/UCTutils.o \
		src/Bandits/UCBK.o \
		src/Bandits/UCBKV.o \
		src/Bandits/UCBKRandomized.o \
		src/Bandits/Random.o \
		src/Bandits/Exp3.o \
		src/Bandits/Exp3G.o \
		src/WeakLearners/BaseLearner.o \
		src/WeakLearners/ConstantLearner.o \
		src/WeakLearners/FeaturewiseLearner.o \
		src/WeakLearners/AbstainableLearner.o \
		src/WeakLearners/SingleStumpLearner.o \
		src/WeakLearners/SingleStumpLearnerLSHTC.o \
		src/WeakLearners/RandomSingleStumpLearner.o \
		src/WeakLearners/UCB1SingleStumpLearner.o \
		src/WeakLearners/UCBKSingleStumpLearner.o \
		src/WeakLearners/BanditSingleStumpLearner.o \
		src/WeakLearners/UCBKSingleStumpLearnerLSHTC.o \
		src/WeakLearners/UCBVHaarSingleStumpLearner.o \
		src/WeakLearners/DirichletSingleStumpLearner.o \
		src/WeakLearners/MultiStumpLearner.o \
		src/WeakLearners/ParasiteLearner.o \
		src/WeakLearners/ProductLearner.o \
		src/WeakLearners/ProductLearnerLSHTC.o \
		src/WeakLearners/ProductLearnerUCT.o \
		src/WeakLearners/TreeLearner.o \
		src/WeakLearners/TreeLearnerUCT.o \
		src/WeakLearners/EnumLearner.o \
		src/WeakLearners/Selector.o \
		src/WeakLearners/Haar/HaarLearner.o \
		src/WeakLearners/Haar/HaarFeatures.o \
		src/WeakLearners/HaarSingleStumpLearner.o \
		src/WeakLearners/HaarMultiStumpLearner.o \
		src/main.o
INTERFACES =	
UICDECLS =	
UICIMPLS =	
SRCMOC	=	
OBJMOC	=	
DIST	=	
TARGET	=	multiboost
INTERFACE_DECL_PATH = .

####### Implicit rules

.SUFFIXES: .cpp .cxx .cc .C .c

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules


all: $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

moc: $(SRCMOC)

#tmake: Makefile

#Makefile: multiboost.pro
#	tmake multiboost.pro -o Makefile

dist:
	$(TAR) multiboost.tar multiboost.pro $(SOURCES) $(HEADERS) $(INTERFACES) $(DIST)
	$(GZIP) multiboost.tar

clean:
	-rm -f $(OBJECTS) $(OBJMOC) $(SRCMOC) $(UICIMPLS) $(UICDECLS) $(TARGET)
	-rm -f *~ core

####### Sub-libraries


###### Combined headers


####### Compile

src/StrongLearners/AdaBoostMHLearner.o: src/StrongLearners/AdaBoostMHLearner.cpp

src/Classifiers/AdaBoostMHClassifier.o: src/Classifiers/AdaBoostMHClassifier.cpp

src/Classifiers/ExampleResults.o: src/Classifiers/ExampleResults.cpp

src/Algorithms/ConstantAlgorithm.o: src/Algorithms/ConstantAlgorithm.cpp \
		src/Algorithms/ConstantAlgorithm.h

src/Algorithms/ConstantAlgorithmLSHTC.o: src/Algorithms/ConstantAlgorithmLSHTC.cpp \
		src/Algorithms/ConstantAlgorithmLSHTC.h

src/IO/NameMap.o: src/IO/NameMap.cpp \
		src/IO/NameMap.h

src/IO/InputData.o: src/IO/InputData.cpp

src/IO/RawData.o: src/IO/RawData.cpp

src/IO/EncodeData.o: src/IO/EncodeData.cpp

src/IO/OutputInfo.o: src/IO/OutputInfo.cpp

src/IO/Serialization.o: src/IO/Serialization.cpp

src/IO/SortedData.o: src/IO/SortedData.cpp \
		src/IO/SortedData.h

src/IO/HaarData.o: src/IO/HaarData.cpp \
		src/IO/HaarData.h

src/IO/TxtParser.o: src/IO/TxtParser.cpp

src/IO/ArffParser.o: src/IO/ArffParser.cpp

src/IO/LSHTCParser.o: src/IO/LSHTCParser.cpp

src/IO/ArffParserBzip2.o: src/IO/ArffParserBzip2.cpp \
		src/IO/ArffParserBzip2.h

src/Bzip2/Bzip2Wrapper.o : src/Bzip2/Bzip2Wrapper.cpp \
		src/Bzip2/Bzip2Wrapper.h

src/Utils/Args.o: src/Utils/Args.cpp \
		src/Utils/Args.h

src/Utils/Utils.o: src/Utils/Utils.cpp \
		src/Utils/Utils.h

src/Utils/ClassHierarchy.o: src/Utils/ClassHierarchy.cpp \
		src/Utils/ClassHierarchy.h

src/Utils/Utils.o: src/Utils/UCTutils.cpp \
		src/Utils/UCTutils.h

src/WeakLearners/BaseLearner.o: src/WeakLearners/BaseLearner.cpp

src/WeakLearners/ConstantLearner.o: src/WeakLearners/ConstantLearner.cpp \
		src/WeakLearners/ConstantLearner.h

src/WeakLearners/FeaturewiseLearner.o: src/WeakLearners/FeaturewiseLearner.cpp

src/WeakLearners/AbstainableLearner.o: src/WeakLearners/AbstainableLearner.cpp

src/WeakLearners/SingleStumpLearner.o: src/WeakLearners/SingleStumpLearner.cpp \
		src/WeakLearners/SingleStumpLearner.h \
		src/Algorithms/StumpAlgorithm.h

src/WeakLearners/SingleStumpLearnerLSHTC.o: src/WeakLearners/SingleStumpLearnerLSHTC.cpp \
		src/WeakLearners/SingleStumpLearnerLSHTC.h \
		src/Algorithms/StumpAlgorithmLSHTC.h

src/WeakLearners/RandomSingleStumpLearner.o: src/WeakLearners/RandomSingleStumpLearner.cpp \
		src/WeakLearners/RandomSingleStumpLearner.h \
		src/Algorithms/StumpAlgorithm.h

src/WeakLearners/MultiStumpLearner.o: src/WeakLearners/MultiStumpLearner.cpp \
		src/WeakLearners/MultiStumpLearner.h \
		src/Algorithms/StumpAlgorithm.h

src/WeakLearners/ParasiteLearner.o: src/WeakLearners/ParasiteLearner.cpp \
		src/WeakLearners/ParasiteLearner.h

src/WeakLearners/ProductLearner.o: src/WeakLearners/ProductLearner.cpp \
		src/WeakLearners/ProductLearner.h

src/WeakLearners/ProductLearnerLSHTC.o: src/WeakLearners/ProductLearnerLSHTC.cpp \
		src/WeakLearners/ProductLearnerLSHTC.h

src/WeakLearners/ProductLearnerUCT.o: src/WeakLearners/ProductLearnerUCT.cpp \
		src/WeakLearners/ProductLearnerUCT.h

src/WeakLearners/TreeLearner.o: src/WeakLearners/TreeLearner.cpp \
		src/WeakLearners/TreeLearner.h

src/WeakLearners/EnumLearner.o: src/WeakLearners/EnumLearner.cpp \
		src/WeakLearners/EnumLearner.h

src/WeakLearners/Selector.o: src/WeakLearners/Selector.cpp \
		src/WeakLearners/Selector.h

src/WeakLearners/Haar/HaarLearner.o: src/WeakLearners/Haar/HaarLearner.cpp \
		src/WeakLearners/Haar/HaarLearner.h

src/WeakLearners/Haar/HaarFeatures.o: src/WeakLearners/Haar/HaarFeatures.cpp \
		src/WeakLearners/Haar/HaarFeatures.h

src/WeakLearners/HaarSingleStumpLearner.o: src/WeakLearners/HaarSingleStumpLearner.cpp \
		src/WeakLearners/HaarSingleStumpLearner.h

src/WeakLearners/HaarMultiStumpLearner.o: src/WeakLearners/HaarMultiStumpLearner.cpp \
		src/WeakLearners/HaarMultiStumpLearner.h

src/main.o: src/main.cpp \
		src/Defaults.h \
		src/Utils/Args.h \
		src/StrongLearners/GenericStrongLearner.h \
		src/WeakLearners/BaseLearner.h \
		src/Utils/StreamTokenizer.h \
		src/Classifiers/AdaBoostMHClassifier.h \
		src/IO/NameMap.h \
		src/IO/Serialization.h \
		src/Utils/Utils.h

